### ISSUE TITLE
Firefox throws "no element found" exception on log()

### ISSUE THREAD

**Issue by omichelsen** [logentries/le_js#24]
Since the POST to LogEntries return an empty response (no content), Firefox apparently throws a "no element found" exception each time we log something.

**Comment by louis77** [comment]
I have the same issue here on Firefox and it's pretty disturbing. Is there any fix on this to be expected?

**Comment by m0wfo** [comment]
@omichelsen, @louis77 This stems from a [long](https://bugzilla.mozilla.org/show_bug.cgi?id=547718) [list](https://bugzilla.mozilla.org/show_bug.cgi?id=884693) of [bugs](https://groups.google.com/forum/#!topic/mithriljs/1unmja9hfmE) relating to `204` responses in Firefox, which Mozilla seems to have no intention of fixing.

Given that, and the fact that the actual log payload seems to successfully send, we have a couple of options:

1. Close, mark as *wontfix*
2. Wrap the XHR request execution in a try/catch to suppress the exception
3. Change our API, which is a possibility but we'd have to ensure it breaks nothing first

Opinions guys?

**Comment by costint** [comment]
#2 seems like it would be the fastest option, as well as maybe a best practice to trap any other errors that could occur during the XHR request to ensure it doesn't impact the host application.

**Comment by bathos** [comment]
It's not an exception -- a try block won't have anything to catch (plus xhr is async...). It's a notice triggered by the traffic, outside the domain of any scripts executing.

**Comment by costint** [comment]
Ok, in that case #3 is the only option.

**Comment by bathos** [comment]
Forgot to close this -- addressed at https://github.com/logentries/le_js/commit/c1a11288564de0864fba458b88c011e4b7b929f1 .

In case anyone is curious why that works, or wonders why that seemingly nonsensical statement is there in the future:

 - Firefox has a bug where 204 responses are not handled correctly internally. It tries to read a body even though 204 is expressly defined as not having a body, and that if one exists, it should be ignored. (https://tools.ietf.org/html/rfc2616#section-10.2.5)
 - Firefox has a second, unrelated bug where responses with no Content-Type header default to "xml". The correct default is octet stream. (https://tools.ietf.org/html/rfc2616#section-7.2.1)
 - The two bugs together mean that it tries and fails to read an XML body that does not exist. Although this does not result in an exception or other programmatic consequences, it logs a network notice saying it didn't find a root element.
 - We can trick Firefox into displaying no message by overriding the response mime type. Since the only body it will find is an empty string, which is invalid XML, we instead tell it that the content-type is text. An empty string is valid text, so it stays silent. It's a bit of a hack; a 204 shouldn't have a content-type header (though it's not illegal). RFC compliant browsers will just ignore it, so as hacks go it's pretty clean and harmless.

Presumably Firefox will fix this ... eventually. When/if they do, the mimetype override should be removed.

**Comment by m0wfo** [comment]
Thanks @bathos :)

**Comment by atlesp** [comment]
Is  this fix released yet? I see the product folder that the doc state we should grab it from is not updated in 5 months.
![image](https://cloud.githubusercontent.com/assets/1275067/8228436/e83b65f8-15ae-11e5-9de9-f2b2fd023953.png)

**Comment by bathos** [comment]
Looks like m0wf' just fixed that, @atlesp. This was my first time fiddling around in le_js and I hadn't realized we kept built versions in the repo.

**Comment by atlesp** [comment]
thanks @m0wfo  and @bathos :)
