### ISSUE TITLE
option to use the data.logentries.com endpoint

### ISSUE THREAD

**Issue by chrismatheson** [logentries/le_js#36]
i would like to see an option where the internal log object was sent to `data.logentries.com` instead of `js.logentries.com` so that it will be nicely searchable / formatted in the LE web ui, as described here https://blog.logentries.com/2014/09/3-common-problems-solved-with-json/

*problems*

the `data.logentries.com` does not end a http connection the same as `js.logentries.com` does. So there would need to be some way of figuring out when the sent data has actually made it to logs before forcing a connection close from the client end

*advatanges*

however one single long lived TCP connection would be more power efficient that multiple HTTP POST requests so we should see some enhancement in power usage #4  

would this be a useful addition to the library? @m0wfo ?

**Comment by chrismatheson** [comment]
Just an FYI, I've been tasked at work to implement client side logging for our hybrid application (node-webkit desktop + apache cordova iOS) so power management, offline logging etc are high on my priority list and i would very much like to see any enhancements i can make it back into this open source lib if possible, so please let me know any thoughts etc anyone has on direction

**Comment by StephenHynes7** [comment]
@chrismatheson else maybe we could add an option for the js.logentries.com JSONfy the full message? @m0wfo what do you think?

**Comment by m0wfo** [comment]
Kind of following on from #40-

While `js.logentries.com` is 'private', not publicly documented and subject to change without notice, we're looking at using the underlying service for other application protocols so cater for this kind of demand. I can't commit to any specifics, timelines, e.t.c. though.

WebSocket support was initially available but removed due to constraints of our load-balancers which are no longer an issue. If you'd find this kind of thing useful (plain TCP, WS, sock.js, socket.io, ...) then again I'd suggest posting a [feature request](https://trello.com/b/ICckMDvF/logentries-feature-request) asking for it.

**Comment by m0wfo** [comment]
Am going to close for now.

**Comment by udangel-r7** [comment]
i think this is also solved by #60
